# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'bstu_service' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bstu_service

  # Required by RNFirebase
  pod 'Firebase/Core'

  target 'bstu_serviceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
